### ISSUE TITLE
SESSDATA的格式是什么啊？

### ISSUE THREAD

**Issue by Thomitics** [xlzy520/picgo-plugin-bilibili#1]
试了`ef0ecf6e%2C16343%2Cf006a*41`和`SESSDATA=ef0ecf6e%2C16343%2Cf006a*41`都不行，都提示“请先登录”

**Comment by xlzy520** [comment]
> 试了`ef0ecf6e%2C16343%2Cf006a*41`和`SESSDATA=ef0ecf6e%2C16343%2Cf006a*41`都不行，都提示“请先登录”

前面这个`ef0ecf6e%2C16343%2Cf006a*41`你用的我之前的SESSDATA，我故意删了几个字符，
关于如何获取SESSDATA，我这里写了
https://github.com/xlzy520/picgo-plugin-bilibili#%E8%8E%B7%E5%8F%96b%E7%AB%99sessdata

我这里也给你一个我自己的：  `ef0ecf6e%2C1634699903%2Cf006a*41`
