### ISSUE TITLE
readme.md增加关于bli_jct的配置

### ISSUE THREAD

**Issue by RuanZhongNan** [xlzy520/picgo-plugin-bilibili#11]
项目首页没有关于bli_jct的配置，在语雀的文章内才能看到该配置。建议同步补齐该内容。

https://www.yuque.com/xlzy520/blog/fydq8g

**Comment by youngwy258** [comment]
Hello, I used your way to upload pictures to station B normally, but yesterday I found that the uploaded pictures could not be displayed normally when I opened them today, as shown below in typora
![image](https://user-images.githubusercontent.com/35211547/220238478-3ea0041d-f1d7-4465-af9e-416d8f57d49a.png)

ps:   Copy the link separately in the browser for access as shown below
![image](https://user-images.githubusercontent.com/35211547/220238597-6b08097d-e41d-4d4e-a3b7-9c2f890396e8.png)
I am sure that it can be displayed after uploading successfully, but the address will be invalid after one night, so the picture cannot be accessed. Please confirm what is going on, online, etc., hope to see your reply. thank you

**Comment by xlzy520** [comment]
好了
