### ISSUE TITLE
上传成功图片到B站，第二天图片地址失效，无法访问

### ISSUE THREAD

**Issue by youngwy258** [xlzy520/picgo-plugin-bilibili#12]
Hello, I used your way to upload pictures to station B normally, but yesterday I found that the uploaded pictures could not be displayed normally when I opened them today, as shown below in typora
![image](https://user-images.githubusercontent.com/35211547/220238860-3efb06bf-8a3e-44b7-9ac1-abfafc2e7be3.png)

ps: Copy the link separately in the browser for access as shown below
![image](https://user-images.githubusercontent.com/35211547/220238887-ce22089d-1fb1-4540-b55b-c9feb932e9bc.png)
I am sure that it can be displayed after uploading successfully, but the address will be invalid after one night, so the picture cannot be accessed. Please confirm what is going on, online, etc., hope to see your reply. thank you

**Comment by xlzy520** [comment]
@youngwy258 使用最新的版本
