### ISSUE TITLE
能否直接转为短连接

### ISSUE THREAD

**Issue by Nigtunt** [xlzy520/picgo-plugin-bilibili#3]
https://i0.hdslb.com/bfs/album/a18a3f8d666dc19c3216bef39a092e0e60c90eb4.png     =>    https://b23.tv/XNADZrW

**Comment by xlzy520** [comment]
@Nigtunt 暂时没有精力完善这个插件，转短链的功能我之前做了一个网站：https://xiaojuzi.fun/bili-short-url/

**Comment by qg46** [comment]
b23短链接只有1年有效期，长期不现实
