### ISSUE TITLE
请教个问题。

### ISSUE THREAD

**Issue by artiely** [xlzy520/picgo-plugin-bilibili#4]
我的图上传的bilibili了我在bilibili哪里可以查看到我的图片？有入口吗。还是在其他地方查看？

**Comment by xlzy520** [comment]
Picgo这边暂时没有管理功能，我的另一个浏览器插件项目是有已上传图片管理功能的
![image](https://user-images.githubusercontent.com/28336270/149440625-8dc84b43-2c70-47cc-84e6-37389c62f1b4.png)
![image](https://user-images.githubusercontent.com/28336270/149440639-4f4a3de1-0a6b-46a6-bd0b-afb50d8907b8.png)

**Comment by xlzy520** [comment]
@artiely https://github.com/xlzy520/bilibili-img-uploader/releases/tag/v2.0.7
