### ISSUE TITLE
更加方便地解决B站防盗链

### ISSUE THREAD

**Issue by Liang457** [xlzy520/picgo-plugin-bilibili#5]
可以使用[Images.weserv.nl](https://images.weserv.nl/)服务来解决该问题(还可以顺便加个速)

只需要在index.js的第56行替换为

```
imgList[i].imgUrl = body.data.image_url.replace('http', 'https://images.weserv.nl/?url=https')
```

即可在上传时自动地换为Images.weserv.nl服务

预览：[加速图片访问|解决图片防盗链](https://www.cool-gk.cn/2022/01/23/%E5%8A%A0%E9%80%9F%E5%9B%BE%E7%89%87%E8%AE%BF%E9%97%AE/#%E5%88%AB%E7%9A%84%E4%B8%80%E4%BA%9B)

**Comment by xlzy520** [comment]
防盗链解决方案这个你可以fork一份进行修改。
然后加速的话，B站的速度在国内已经足够快了。

**Comment by xlzy520** [comment]
不过这个网站很不错，先收藏了

**Comment by Liang457** [comment]
[复刻](https://github.com/Liang457/picgo-plugin-bilibili)了，顺带加了个选项用来选择用不用Images.weserv.nl服务

确实用上这个服务会导致图片加载速度变慢一些

![](https://images.weserv.nl/?url=https://i0.hdslb.com/bfs/album/31888733a6bf89bc11a55947dbd5ca913a678275.png)

**Comment by SnowMeteors** [comment]
> [复刻](https://github.com/Liang457/picgo-plugin-bilibili)了，顺带加了个选项用来选择用不用Images.weserv.nl服务
> 
> 确实用上这个服务会导致图片加载速度变慢一些
> 
> ![](https://camo.githubusercontent.com/c060fb689993e88c9f1ae646f71bf18fd24938151c0f09b5a9e80d23ded415c7/68747470733a2f2f696d616765732e7765736572762e6e6c2f3f75726c3d68747470733a2f2f69302e6864736c622e636f6d2f6266732f616c62756d2f333138383837333361366266383962633131613535393437646264356361393133613637383237352e706e67)

求给一份picgo 带bilibili图床的程序，谢谢您的分享

**Comment by yongweiye** [comment]
目前上传提示403 ，请问如何解决？
