### ISSUE TITLE
<meta name="referrer" content="no-referrer"> 加了还是不行，是因为https的原因吗？

### ISSUE THREAD

**Issue by codeslive** [xlzy520/picgo-plugin-bilibili#7]

**Comment by xlzy520** [comment]
有报错截图吗，有网站地址发一下吗

**Comment by codeslive** [comment]
解决了，原来是没有全局添加

![image](https://user-images.githubusercontent.com/84132355/188262064-3aac2477-0f0b-4687-83d4-f017c0c22b5e.png)
picgo每次重启就会莫名奇妙地上传几张空图片，不知大佬知不知道怎么解决

**Comment by xlzy520** [comment]
@codeslive 这个应该是picgo自身的问题

**Comment by qg46** [comment]
> 解决了，原来是没有全局添加
> 
> ![image](https://user-images.githubusercontent.com/84132355/188262064-3aac2477-0f0b-4687-83d4-f017c0c22b5e.png) picgo每次重启就会莫名奇妙地上传几张空图片，不知大佬知不知道怎么解决

我勒个1140，你比我薅的还狠啊
